### ISSUE TITLE
Highly increased CPU load when changing sample rate or buffer size

### ISSUE THREAD

**Issue by randyjonesworld** [madronalabs/sumu-issues#10]
Environment
Sumu 1.0.0b9
Win 10 Home 19045
Ableton Live 11.3.22
Ryzen 7800X3D
Focusrite Scarlett

Steps to reproduce
1. Load Sumu
2. go to preferences and change the sample rate or change the buffer size in the Focusrite hardware setup.

Expected behavior
I would expect the CPU usage to go down when I decrease the sample rate or increase the buffer size.

Actual behavior
The CPU load increases drastically.
Deleting and reloading Sumu will solve the issue and get the CPU load to where it should be.
(Setting the sample rate or buffer size back to their original settings without reloading Sumu will increase the CPU load even more.)

**Comment by Enkerli** [comment]
Similar issue… even without changing the sample rate or buffer size.

# Environment
Sumu 1.0.0b20 (VST3, ARM)
macOS Sequoia 15.1b3
Bitwig Studio 5.2.3
MacBook Air M1, 16GB
Arturia MiniFuse 2

# Steps to reproduce
1. Load Sumu
2. Check the CPU load

# Expected behaviour 
I would expect the CPU usage for Sumu to be similar to that of other plugins, e.g. Aalto, especially at low sample rate and/or high buffer size.

# Observed behaviour 
Upon loading Sumu, even before playing a single note, the CPU load peaks. Even at the lowest sample rate (44.1kHz) and at a relatively large buffer size (512 samples).

Same issue in Logic Pro (11.0.1).

https://github.com/user-attachments/assets/712a3540-53b3-49ed-a976-6ab334d81632

**Comment by randyjonesworld** [comment]
Thanks but not a bug—the plugin is simply CPU-heavy and not well optimized now.
